<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About</name>
   <tag></tag>
   <elementGuidId>2bd25587-c06d-4f4a-bbbb-47f9e498c5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pg238060751361913988 > a.wsite-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pg238060751361913988']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ef432f5-05c1-43a9-8579-03a9ddcf7bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/about.html</value>
      <webElementGuid>6c5257e4-8d6e-46f2-bccf-6f918d4a6004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsite-menu-item</value>
      <webElementGuid>a22574cb-625e-48be-adc4-d96a12c4ad30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				About
			</value>
      <webElementGuid>cfba42cc-0cfb-403f-993c-f48770df7956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-page  wsite-page-index  full-width-body-off header-overlay-off alt-nav-off  wsite-theme-light fade-in&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;birdseye-header&quot;]/div[@class=&quot;nav-wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;nav desktop-nav&quot;]/ul[@class=&quot;wsite-menu-default&quot;]/li[@id=&quot;pg238060751361913988&quot;]/a[@class=&quot;wsite-menu-item&quot;]</value>
      <webElementGuid>1f8ab0b2-4439-4eee-80b0-4704c78deece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pg238060751361913988']/a</value>
      <webElementGuid>e97fb43c-f91e-4a16-ba9c-f29e1a715f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'About')]</value>
      <webElementGuid>8411c8ba-488a-4cb8-8889-abb1c73c7991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>255a5386-b5e2-4a05-8b03-6f5eb78e202c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WE ARE ALL BOBS'])[1]/following::a[2]</value>
      <webElementGuid>ea73da57-566a-4b30-8eba-7f2ef21e2baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::a[1]</value>
      <webElementGuid>e1a5d450-0b9e-4ac0-b9c9-25e981da3b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[2]</value>
      <webElementGuid>d0235c1d-a9d3-48f0-b4ca-7db357293046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='About']/parent::*</value>
      <webElementGuid>503b7bfd-7a14-4981-95eb-f9f1084ca8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/about.html')]</value>
      <webElementGuid>7fd4df6c-2f01-4598-be9d-43f355d1d9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>b03b0435-e999-48b9-9a17-a22e4a17ff17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/about.html' and (text() = '
				About
			' or . = '
				About
			')]</value>
      <webElementGuid>33f03e6b-f71d-4157-a2fe-1eeb5bdfaa50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
