<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Contact</name>
   <tag></tag>
   <elementGuidId>274cc43a-cb34-4f3f-a743-8caa95b510ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pg241523327124709480 > a.wsite-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='pg241523327124709480']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f699a383-541f-4159-a41f-868d8a8c7c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/contact.html</value>
      <webElementGuid>8d9c8a68-0227-4b31-842b-e4cc3c0ebb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsite-menu-item</value>
      <webElementGuid>0adbbe07-0280-44df-ab1f-0ccc18ca166d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Contact
			</value>
      <webElementGuid>e9f5b354-9481-4c01-aa7f-87c3b66e24ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;header-page  wsite-page-index  full-width-body-off header-overlay-off alt-nav-off  wsite-theme-light fade-in&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;birdseye-header&quot;]/div[@class=&quot;nav-wrap&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;nav desktop-nav&quot;]/ul[@class=&quot;wsite-menu-default&quot;]/li[@id=&quot;pg241523327124709480&quot;]/a[@class=&quot;wsite-menu-item&quot;]</value>
      <webElementGuid>cd58853c-8299-450e-901c-7d8a6f085fc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='pg241523327124709480']/a</value>
      <webElementGuid>18489034-4252-4c4c-b55a-a893890d412b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Contact')]</value>
      <webElementGuid>697eb1db-0dc4-491e-b3cd-dd62e69e293e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::a[1]</value>
      <webElementGuid>ccedab2c-3e57-4882-a783-df45a1e18ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::a[2]</value>
      <webElementGuid>48187bcb-546b-4058-bd68-541f05f50d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Casual Runs'])[1]/preceding::a[2]</value>
      <webElementGuid>4d65fb86-2c3b-4d59-b6cf-97da99778d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact']/parent::*</value>
      <webElementGuid>eeb3c666-e464-43b6-bc2c-2b6b8768414a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/contact.html')]</value>
      <webElementGuid>51485aea-abbb-4fb3-bb27-2bf86ab4a91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>deaf570f-6533-4204-aa6d-1ef5be0617f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/contact.html' and (text() = '
				Contact
			' or . = '
				Contact
			')]</value>
      <webElementGuid>93ea5a35-39d2-42b2-af05-edc2445cd29a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
